# 角色资源访问权限映射
resource:
  role-map:
    - id: 0
      name: USER
    - id: 1
      name: ADMIN

  path-role-map:
    - path: /api/user
      role:
        - ROLE_ADMIN
        - ROLE_USER
        - ROLE_TEST
    - path: /api/video
      role:
        - ROLE_ADMIN
        - ROLE_USER
        - ROLE_TEST
    - path: /api/interact
      role:
        - ROLE_ADMIN
        - ROLE_USER
        - ROLE_TEST
    - path: /api/oss
      role:
        - ROLE_ADMIN
        - ROLE_USER
        - ROLE_TEST
    - path: /ws/oss
      role:
        - ROLE_ADMIN
        - ROLE_USER
        - ROLE_TEST

security-config:
  ignore-url-list:
    - /rsa/publicKey
    - /crypto/**
    - /session/**
