server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 20000
    keep-alive-timeout: 60000   # 不知道为什么connection: keep-alive没生效，一直是close
    threads:
      max: 400
      min-spare: 10

resource:
  role-map:
    - id: 0
      name: ROLE_USER
    - id: 1
      name: ROLE_ADMIN

  path-role-map:
    - path: /api/user
      role:
        - ROLE_ADMIN
        - ROLE_USER
        - ROLE_TEST
    - path: /api/video
      role:
        - ROLE_ADMIN
