security-config:
#  鉴权访问白名单
  ignore-url-list:
    - /auth/crypto/**
    - /auth/session/**
    - /static/**
    - /api/user/register
    - /doc.html
    - /webjars/**
    - /favicon.ico
    - /v3/api-docs/**
    - /doc/**