server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 20000
    keep-alive-timeout: 60000   # 不知道为什么connection: keep-alive没生效，一直是close
    threads:
      max: 400
      min-spare: 10

security-config:
#  鉴权访问白名单
  ignore-url-list:
    - /static/**
    - /auth/session/**
    - /api/user/register
    - /doc.html
    - /webjars/**
    - /favicon.ico
    - /v3/api-docs/**
    - /doc/**